spring:
  application:
    name: zuulService

server:
  port: 8086
  ssl:
    enabled: true
    key-store: ${KEY_STORE_CLASSPATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: zuul
    trust-store: ${KEY_STORE_CLASSPATH_TRUST}
    trust-store-password: ${KEY_STORE_TRUST_PASSWORD}
  
eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    prefer-ip-address: false
    securePortEnabled: true
    securePort: ${server.port}
 
    
zuul:
  routes:
    kpService:
      serviceId: kpService
    authService:
      serviceId: authService
    config-server:
      serviceId: config-server
    bitcoinService:
      serviceId: bitcoinService
    bankService:
      serviceId: bankService
    payPalService:
      serviceId: payPalService
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
               
ribbon:
  ReadTimeout: 60000
      
   