spring:
  application:
    name: zuulService

server:
  port: 8086
  ssl:
    enabled: true
    key-store: ${KEY_STORE_CLASSPATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: zuul
    trust-store: ${KEY_STORE_CLASSPATH_TRUST}
    trust-store-password: ${KEY_STORE_TRUST_PASSWORD}
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka}
    registerWithEureka: true   #dodala
    fetchRegistry: true         #dodala
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    prefer-ip-address: false      #izmenila bilo false
    securePortEnabled: true
    securePort: ${server.port}
 
    
zuul:
  routes:
    kpService:
      serviceId: kpService
    authService:
      serviceId: authService
    config-server:
      serviceId: config-server
    bitcoinService:
      serviceId: bitcoinService
    bankService:
      serviceId: bankService
    payPalService:
      serviceId: payPalService
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
               
ribbon:
  eureka:            #dodala
     enabled : true #dodala
  ReadTimeout: 600000
      
security:
  require-ssl: true   