spring:
  application:
    name: zuulService

server:
  port: 8086
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    prefer-ip-address: false
    securePortEnabled: true
    securePort: ${server.port}
 
    
zuul:
  routes:
    kpService:
      serviceId: kpService
    authService:
      serviceId: authService
    config-server:
      serviceId: config-server
      
   