spring:
  application:
    name: eurekaService
    
server:
  port: 8761
  ssl:
    enabled: true  
    key-store-type: JKS
    key-store-provider: SUN
    key-store: ${KEY_STORE_CLASSPATH}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-alias: eureka
    trust-store: ${KEY_STORE_CLASSPATH_TRUST}
    trust-store-password: ${KEY_STORE_TRUST_PASSWORD}
    protocol: TLS
    enabled-protocols: TLSv1.2
    #client-auth: need
  
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://localhost:8761/eureka}
    registerWithEureka: false
    fetchRegistry: false 

logging:
  #config: classpath:logback.xml 
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
