spring:
  application:
    name: eurekaService
    
server:
  port: 8761
  
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: http://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/admin/info
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: false
    fetchRegistry: false 

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
