spring:
  application:
    name: bankAcquirer 
  datasource:
    url: jdbc:mysql://localhost:3306/bankIssuer?useSSL=false&createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: sifra
    driverClassName : com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform : org.hibernate.dialect.MySQL5Dialect 

server:
  port: 8092